### ISSUE TITLE
feat: style secondary blocks

### ISSUE THREAD

**Issue by ramboz** [hlxsites/rolex-event#21]
The Rolex design system defines some secondary blocks styles:
<img width="1459" alt="Screenshot 2022-11-24 at 9 52 31 AM" src="https://user-images.githubusercontent.com/1235810/203736487-eedee5cd-6d77-4f6b-9e9a-b8a40afce480.png">

Can be seen on http://rlxntr2022.ocitocine.com/pages/layouts/intranet/who.html for instance, or in the XD file under the "minisite" components (bottom center).

We have a few good candidates for this on our pages:
- /en/rolex-booth
- /en/evening-events
- /en/transfers
- /en/accreditations

The Download portal and Useful links blocks would make great examples. Also on the French pages.

I think there are 2 ways to achieve this:
1. Isolate the content in a dedicated section, and use a "Section Metadata" block to define a style property we can target in CSS. See https://www.hlx.live/developer/markup-sections-blocks#sections
2. Wrap the content in a dedicated block that will get it's custom styling

I'd be tempted to go with 1. as it makes authoring the content easier

**Comment by solaris007** [comment]
Lets first tackle the two utility boxes in the third column:
![Screenshot 2022-11-25 at 07 00 12](https://user-images.githubusercontent.com/1872195/203911420-1bdeef0a-0c43-446e-aa08-e2d07f3cf588.png)

It seems to me there's no direct equivalent in the Rolex Design System. For both the Downloads and the Useful Links we could use the design for "Liens Rapids" present on the left on this page: http://rlxntr2022.ocitocine.com/pages/layouts/intranet/space-empty.html

![Screenshot 2022-11-25 at 06 55 06](https://user-images.githubusercontent.com/1872195/203911546-9a3c88ae-3659-421d-a6ff-534a746ec597.png)

WDYT? @ramboz @ekremney @nicolasbarbe

**Comment by solaris007** [comment]
Also more general question: @ekremney is working on layouting and currently the content is in three columns:
![Screenshot 2022-11-25 at 07 13 05](https://user-images.githubusercontent.com/1872195/203913059-31d2949c-9dd6-4edc-a0a3-9ae8f66adbac.png)

Our goal however is to use sections with metadata for each of the functional blocks. So i'd imagine that no longer three columns are used in Word, but each block is a section with metadata that are arranged by layouting accordingly.

How does that match with what's going on @ramboz @ekremney ?

**Comment by ramboz** [comment]
@solaris007 Not sure I'd go with the quick links design immediately. Let's wait for their input on Monday. I'd have started with the sidebar boxes from the 1st image first since this is more discrete.

I would also advise against using the columns block for layouting at this point. There are a few issues with it:
- it won't play nice with the grid layout we wanted and the "aside" column
- it won't play that nice on mobile as we have an opinionated rendering imposed in the default block (can't mix and match columns, or resize them easily at different breakpoints)
- it renders async, meaning you'll see flickering and likely have CLS at least on desktop
- it injects a lot of JS for something that is achievable via CSS alone

I'd be tempted to rather do a combination of:
- Template prop on the home page metadata block
- keep the current "last section" as the aside block for the links
- leave the rest in the main content section and lay out the blocks using one of [CSS Columns](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns) or [Flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout)

**Comment by solaris007** [comment]
alright, we lock in the design for useful links and downloads blocks with:
![Screenshot 2022-11-25 at 07 36 21](https://user-images.githubusercontent.com/1872195/203916073-2494deab-0025-4aaa-ac5f-ba69f8905f1c.png)

Pending any design changes on Monday.
